// 11 Eylül 2026 (Kerem: "ülke isimleri İngilizce geliyor. Netherlands gibi.
// Türkçe olmalı.") — veri setinin kendisi (lib/countries.json) Wikipedia
// kaynaklı olduğu için ülkeleri İngilizce tutuyor ve BU DOĞRU: eşleştirme,
// bayrak ve milli takım verisi hep o İngilizce anahtar üzerinden çalışıyor.
// Bu dosya sadece EKRANDA GÖSTERİM ve KULLANICI GİRDİSİ için Türkçe karşılık
// sağlıyor — veri modeli hiç değişmiyor.
//
// Listede olmayan bir ülke gelirse İngilizce adı olduğu gibi gösterilir
// (hiçbir şey kırılmaz).
export const COUNTRY_TR = {
  Turkey: "Türkiye",
  England: "İngiltere",
  Germany: "Almanya",
  France: "Fransa",
  Spain: "İspanya",
  Italy: "İtalya",
  Portugal: "Portekiz",
  Netherlands: "Hollanda",
  Belgium: "Belçika",
  Brazil: "Brezilya",
  Argentina: "Arjantin",
  Uruguay: "Uruguay",
  Croatia: "Hırvatistan",
  Serbia: "Sırbistan",
  Poland: "Polonya",
  "Czech Republic": "Çekya",
  Austria: "Avusturya",
  Switzerland: "İsviçre",
  Denmark: "Danimarka",
  Sweden: "İsveç",
  Norway: "Norveç",
  Ukraine: "Ukrayna",
  Russia: "Rusya",
  Greece: "Yunanistan",
  Wales: "Galler",
  Scotland: "İskoçya",
  "Northern Ireland": "Kuzey İrlanda",
  "Republic of Ireland": "İrlanda",
  Romania: "Romanya",
  Hungary: "Macaristan",
  Slovakia: "Slovakya",
  Slovenia: "Slovenya",
  "Bosnia and Herzegovina": "Bosna-Hersek",
  Montenegro: "Karadağ",
  "North Macedonia": "Kuzey Makedonya",
  Albania: "Arnavutluk",
  Bulgaria: "Bulgaristan",
  Finland: "Finlandiya",
  Iceland: "İzlanda",
  Georgia: "Gürcistan",
  Armenia: "Ermenistan",
  Azerbaijan: "Azerbaycan",
  Israel: "İsrail",
  Kosovo: "Kosova",
  Cyprus: "Kıbrıs",
  Malta: "Malta",
  Luxembourg: "Lüksemburg",
  Estonia: "Estonya",
  Latvia: "Letonya",
  Lithuania: "Litvanya",
  Moldova: "Moldova",
  Belarus: "Belarus",
  Morocco: "Fas",
  Algeria: "Cezayir",
  Tunisia: "Tunus",
  Egypt: "Mısır",
  Senegal: "Senegal",
  Nigeria: "Nijerya",
  Ghana: "Gana",
  "Ivory Coast": "Fildişi Sahili",
  Cameroon: "Kamerun",
  Mali: "Mali",
  "South Africa": "Güney Afrika",
  "DR Congo": "Demokratik Kongo",
  Congo: "Kongo",
  Zambia: "Zambiya",
  Guinea: "Gine",
  "Burkina Faso": "Burkina Faso",
  Gabon: "Gabon",
  "Cape Verde": "Cape Verde",
  Angola: "Angola",
  Tanzania: "Tanzanya",
  Kenya: "Kenya",
  Uganda: "Uganda",
  "Equatorial Guinea": "Ekvator Ginesi",
  Togo: "Togo",
  Benin: "Benin",
  Mauritania: "Moritanya",
  Libya: "Libya",
  Sudan: "Sudan",
  Zimbabwe: "Zimbabve",
  Mozambique: "Mozambik",
  Namibia: "Namibya",
  Botswana: "Botsvana",
  Comoros: "Komorlar",
  Gambia: "Gambiya",
  "Sierra Leone": "Sierra Leone",
  Rwanda: "Ruanda",
  Niger: "Nijer",
  Chad: "Çad",
  Ethiopia: "Etiyopya",
  Liberia: "Liberya",
  Eswatini: "Esvatini",
  Lesotho: "Lesotho",
  Burundi: "Burundi",
  Madagascar: "Madagaskar",
  Malawi: "Malavi",
  Mexico: "Meksika",
  "United States": "Amerika Birleşik Devletleri",
  Canada: "Kanada",
  Colombia: "Kolombiya",
  Chile: "Şili",
  Peru: "Peru",
  Ecuador: "Ekvador",
  Paraguay: "Paraguay",
  Bolivia: "Bolivya",
  Venezuela: "Venezuela",
  "Costa Rica": "Kosta Rika",
  Jamaica: "Jamaika",
  Panama: "Panama",
  Honduras: "Honduras",
  "El Salvador": "El Salvador",
  Guatemala: "Guatemala",
  "Trinidad and Tobago": "Trinidad ve Tobago",
  Haiti: "Haiti",
  "Curaçao": "Curaçao",
  Japan: "Japonya",
  "South Korea": "Güney Kore",
  Australia: "Avustralya",
  "Saudi Arabia": "Suudi Arabistan",
  Iran: "İran",
  Iraq: "Irak",
  Qatar: "Katar",
  "United Arab Emirates": "Birleşik Arap Emirlikleri",
  Jordan: "Ürdün",
  China: "Çin",
  India: "Hindistan",
  Kazakhstan: "Kazakistan",
  Uzbekistan: "Özbekistan",
  "New Zealand": "Yeni Zelanda",
  Lebanon: "Lübnan",
  Syria: "Suriye",
  Kuwait: "Kuveyt",
  Bahrain: "Bahreyn",
  Oman: "Umman",
  Palestine: "Filistin",
  Vietnam: "Vietnam",
  Thailand: "Tayland",
  Indonesia: "Endonezya",
  Malaysia: "Malezya",
  "North Korea": "Kuzey Kore",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Liechtenstein: "Liechtenstein",
  Gibraltar: "Cebelitarık",
  "Faroe Islands": "Faroe Adaları",
  Monaco: "Monako",
  Bahamas: "Bahamalar",
  Barbados: "Barbados",
  Cuba: "Küba",
  "Dominican Republic": "Dominik Cumhuriyeti",
  "Puerto Rico": "Porto Riko",
  Bermuda: "Bermuda",
  Guyana: "Guyana",
  Suriname: "Surinam",
  Belize: "Belize",
  Nicaragua: "Nikaragua",
  Dominica: "Dominika",
  Grenada: "Grenada",
  "Saint Lucia": "Saint Lucia",
  Aruba: "Aruba",
  "Cayman Islands": "Cayman Adaları",
  "Antigua and Barbuda": "Antigua ve Barbuda",
  Fiji: "Fiji",
  "Papua New Guinea": "Papua Yeni Gine",
  "Solomon Islands": "Solomon Adaları",
  Vanuatu: "Vanuatu",
  Tahiti: "Tahiti",
  "New Caledonia": "Yeni Kaledonya",
  Samoa: "Samoa",
  Tonga: "Tonga",
  "American Samoa": "Amerikan Samoası",
  "Cook Islands": "Cook Adaları",
  Guam: "Guam",
  Kyrgyzstan: "Kırgızistan",
  Tajikistan: "Tacikistan",
  Turkmenistan: "Türkmenistan",
  Afghanistan: "Afganistan",
  Mongolia: "Moğolistan",
  Nepal: "Nepal",
  Bangladesh: "Bangladeş",
  Pakistan: "Pakistan",
  "Sri Lanka": "Sri Lanka",
  Myanmar: "Myanmar",
  Cambodia: "Kamboçya",
  Laos: "Laos",
  Brunei: "Brunei",
  Philippines: "Filipinler",
  Singapore: "Singapur",
  Maldives: "Maldivler",
  Bhutan: "Butan",
  "East Timor": "Doğu Timor",
  "Hong Kong": "Hong Kong",
  "Chinese Taipei": "Çin Tayvanı",
  Macau: "Makao",
  Yemen: "Yemen",
  Somalia: "Somali",
  Djibouti: "Cibuti",
  Eritrea: "Eritre",
  "South Sudan": "Güney Sudan",
  "Central African Republic": "Orta Afrika Cumhuriyeti",
  "São Tomé and Príncipe": "São Tomé ve Príncipe",
  Seychelles: "Seyşeller",
  Mauritius: "Mauritius",
  "Guinea-Bissau": "Gine-Bissau",
  Martinique: "Martinik",
  Guadeloupe: "Guadeloupe",
  "East Germany": "Doğu Almanya",
};

// Ekranda gösterilecek ad. Türkçesi yoksa İngilizcesi döner.
export function countryTr(country) {
  if (!country) return "";
  return COUNTRY_TR[country] || country;
}

// Türkçe ad -> İngilizce (kanonik) ad. Kullanıcı "Hollanda" yazdığında
// veri setindeki "Netherlands" kaydını bulabilmek için.
export const TR_TO_CANONICAL = {};
for (const [en, tr] of Object.entries(COUNTRY_TR)) {
  TR_TO_CANONICAL[tr] = en;
}
