// 31 Ağustos 2026 — Kerem'in kendi bilgisayarından temin edip
// assets/player_photos_custom/ klasörüne koyduğu resimler için OTOMATİK
// ÜRETİLMİŞ eşleme dosyası (bkz. lib/playerPhotos.js — resolvePlayerPhotoUrl
// bu haritaya Supabase/CloudFront'tan ÖNCE bakıyor).
//
// ÖNEMLİ 1: React Native/Metro'da require() DİNAMİK OLAMAZ
// (require(`./${isim}.png`) ÇALIŞMAZ) — bu yüzden her resim için AYRI AYRI,
// statik bir require(...) satırı gerekiyor. Kerem yeni bir resim eklediğinde
// bu dosyaya YENİ BİR SATIR eklenip cihaza yeniden yazılması gerekir (bu iş
// Claude tarafından yapılır, Kerem sadece resmi klasöre koyar).
//
// ÖNEMLİ 2: require(".../foo.png") tek başına bir URI STRING'İ DEĞİL, bir
// asset modülü (packager'a özel bir referans) döndürür. Projedeki her yer
// (components/PlayerPhoto.js dahil) resolvePlayerPhotoUrl'in DÜZ BİR STRING
// URI döndürmesini bekliyor (<Image source={{ uri }} />) — bu yüzden
// Image.resolveAssetSource(...).uri ile asset modülünü gerçek bir URI
// string'ine çeviriyoruz. Böylece bu dosyanın tükettiği taraf hiç
// değişmiyor, resolvePlayerPhotoUrl'in sözleşmesi (her zaman string|null)
// bozulmuyor.
import { Image } from "react-native";

const LOCAL_PLAYER_PHOTO_MODULES = {
  "Armando Güner": require("../assets/player_photos_custom/Armando Güner.png"),
  "Berat Luş": require("../assets/player_photos_custom/Berat Luş.png"),
  "Franck Ribéry": require("../assets/player_photos_custom/Franck Ribéry.png"),
  "İlhan Fakılı": require("../assets/player_photos_custom/İlhan Fakılı.png"),
  "Kerem Atakan Kesgin": require("../assets/player_photos_custom/Kerem Atakan Kesgin.png"),
  "Renato Nhaga": require("../assets/player_photos_custom/Renato Nhaga.png"),
  "Ronaldo": require("../assets/player_photos_custom/Ronaldo.png"),
  "Thierry Henry": require("../assets/player_photos_custom/Thierry Henry.png"),
  "Zinedine Zidane": require("../assets/player_photos_custom/Zinedine Zidane.png"),
  // 31 Ağustos 2026 (Round I) — Kerem'in Transfermarkt ID/foto veritabanından
  // (PlayerIDs.csv + faces/<ID>.png) eşleştirip çektiğimiz ilk parti (12 foto).
  "Phil Foden": require("../assets/player_photos_custom/Phil Foden.png"),
  "N'Golo Kanté": require("../assets/player_photos_custom/N'Golo Kanté.png"),
  "Kobbie Mainoo": require("../assets/player_photos_custom/Kobbie Mainoo.png"),
  "Warren Zaïre-Emery": require("../assets/player_photos_custom/Warren Zaïre-Emery.png"),
  "Senny Mayulu": require("../assets/player_photos_custom/Senny Mayulu.png"),
  "Lawrence Smith": require("../assets/player_photos_custom/Lawrence Smith.png"),
  "Nahuel Ferraresi": require("../assets/player_photos_custom/Nahuel Ferraresi.png"),
  "Paweł Sokół": require("../assets/player_photos_custom/Paweł Sokół.png"),
  "Tyreke Wilson": require("../assets/player_photos_custom/Tyreke Wilson.png"),
  "Omar Yaisien": require("../assets/player_photos_custom/Omar Yaisien.png"),
  "M'Bala Nzola": require("../assets/player_photos_custom/M'Bala Nzola.png"),
  "Jake O'Brien": require("../assets/player_photos_custom/Jake O'Brien.png"),
  // 31 Ağustos 2026 (Round I devamı) — Transfermarkt eşleşmelerinden ikinci parti (7 foto).
  "Danilo D'Ambrosio": require("../assets/player_photos_custom/Danilo D'Ambrosio.png"),
  "Dara O'Shea": require("../assets/player_photos_custom/Dara O'Shea.png"),
  "Matt O'Riley": require("../assets/player_photos_custom/Matt O'Riley.png"),
  "Luke O'Nien": require("../assets/player_photos_custom/Luke O'Nien.png"),
  "Salem M'Bakata": require("../assets/player_photos_custom/Salem M'Bakata.png"),
  "J'Neil Bennett": require("../assets/player_photos_custom/J'Neil Bennett.png"),
  "Konan N'Dri": require("../assets/player_photos_custom/Konan N'Dri.png"),
  // 4 Eylül 2026 (Round 12 devamı) — Kerem'in `foto_eslestir.py`'yi kendi
  // bilgisayarında çalıştırıp assets/player_photos_custom/'a kopyaladığı
  // dev parti (262 foto). Tamamı players.json'daki isimlerle BİREBİR
  // eşleştiği doğrulanarak eklendi (bkz. proje notları — "Jason", "Son",
  // "Stoichkov", "Thuram" gibi tek kelimelik isimler de veri setinde
  // GERÇEKTEN bu şekilde kayıtlı olduğu için doğru, yanlış eşleşme değil).
  "Aaron Peñafiel": require("../assets/player_photos_custom/Aaron Peñafiel.png"),
  "Abdullah Çelik": require("../assets/player_photos_custom/Abdullah Çelik.png"),
  "Agustín Torassa": require("../assets/player_photos_custom/Agustín Torassa.png"),
  "Aiden O'Brien": require("../assets/player_photos_custom/Aiden O'Brien.png"),
  "Aiden O'Neill": require("../assets/player_photos_custom/Aiden O'Neill.png"),
  "Alan Pulido": require("../assets/player_photos_custom/Alan Pulido.png"),
  "Albert Dalmau": require("../assets/player_photos_custom/Albert Dalmau.png"),
  "Alejandro Chumacero": require("../assets/player_photos_custom/Alejandro Chumacero.png"),
  "Alessandro D'Antoni": require("../assets/player_photos_custom/Alessandro D'Antoni.png"),
  "Alessandro Lambrughi": require("../assets/player_photos_custom/Alessandro Lambrughi.png"),
  "Alex Bolaños": require("../assets/player_photos_custom/Alex Bolaños.png"),
  "Alexander Merkel": require("../assets/player_photos_custom/Alexander Merkel.png"),
  "Alexander Pinillo": require("../assets/player_photos_custom/Alexander Pinillo.png"),
  "Alexander Sieghart": require("../assets/player_photos_custom/Alexander Sieghart.png"),
  "Alexandre N'Gadi": require("../assets/player_photos_custom/Alexandre N'Gadi.png"),
  "Alfred N'Diaye": require("../assets/player_photos_custom/Alfred N'Diaye.png"),
  "Ali M'Madi": require("../assets/player_photos_custom/Ali M'Madi.png"),
  "Alípio": require("../assets/player_photos_custom/Alípio.png"),
  "Andrea D'Errico": require("../assets/player_photos_custom/Andrea D'Errico.png"),
  "Andrej Modić": require("../assets/player_photos_custom/Andrej Modić.png"),
  "Andrew Williams": require("../assets/player_photos_custom/Andrew Williams.png"),
  "Andy O'Brien": require("../assets/player_photos_custom/Andy O'Brien.png"),
  "Ange N'Guessan": require("../assets/player_photos_custom/Ange N'Guessan.png"),
  "Antonio D'Alena": require("../assets/player_photos_custom/Antonio D'Alena.png"),
  "Arnau Comas": require("../assets/player_photos_custom/Arnau Comas.png"),
  "Atila Varga": require("../assets/player_photos_custom/Atila Varga.png"),
  "Augusto Seedorf Owusu": require("../assets/player_photos_custom/Augusto Seedorf Owusu.png"),
  "Ayrton Morales": require("../assets/player_photos_custom/Ayrton Morales.png"),
  "Ballou Tabla": require("../assets/player_photos_custom/Ballou Tabla.png"),
  "Bill Robertson": require("../assets/player_photos_custom/Bill Robertson.png"),
  "Carlos Alcaraz": require("../assets/player_photos_custom/Carlos Alcaraz.png"),
  "Carlos Ibáñez": require("../assets/player_photos_custom/Carlos Ibáñez.png"),
  "Cédric N'Koum": require("../assets/player_photos_custom/Cédric N'Koum.png"),
  "Charlie Adams": require("../assets/player_photos_custom/Charlie Adams.png"),
  "Chris Bush": require("../assets/player_photos_custom/Chris Bush.png"),
  "Chris O'Grady": require("../assets/player_photos_custom/Chris O'Grady.png"),
  "Christian Alemán": require("../assets/player_photos_custom/Christian Alemán.png"),
  "Christian Cruz": require("../assets/player_photos_custom/Christian Cruz.png"),
  "Christian D'Urso": require("../assets/player_photos_custom/Christian D'Urso.png"),
  "Christian N'Guessan": require("../assets/player_photos_custom/Christian N'Guessan.png"),
  "Christofer Gonzáles": require("../assets/player_photos_custom/Christofer Gonzáles.png"),
  "D'Mani Mellor": require("../assets/player_photos_custom/D'Mani Mellor.png"),
  "Dani Morer": require("../assets/player_photos_custom/Dani Morer.png"),
  "Daniel Franco": require("../assets/player_photos_custom/Daniel Franco.png"),
  "Daniel O'Shaughnessy": require("../assets/player_photos_custom/Daniel O'Shaughnessy.png"),
  "Daniel Sikorski": require("../assets/player_photos_custom/Daniel Sikorski.png"),
  "Daniel Wein": require("../assets/player_photos_custom/Daniel Wein.png"),
  "Darragh O'Connor": require("../assets/player_photos_custom/Darragh O'Connor.png"),
  "David Norman Jr.": require("../assets/player_photos_custom/David Norman Jr..png"),
  "David O'Leary": require("../assets/player_photos_custom/David O'Leary.png"),
  "Denis D'Onofrio": require("../assets/player_photos_custom/Denis D'Onofrio.png"),
  "Derik Osede": require("../assets/player_photos_custom/Derik Osede.png"),
  "Diawandou Diagne": require("../assets/player_photos_custom/Diawandou Diagne.png"),
  "Dorian Babunski": require("../assets/player_photos_custom/Dorian Babunski.png"),
  "Edoardo Braiati": require("../assets/player_photos_custom/Edoardo Braiati.png"),
  "Edoardo Ceria": require("../assets/player_photos_custom/Edoardo Ceria.png"),
  "Edu Bedia": require("../assets/player_photos_custom/Edu Bedia.png"),
  "Edwin Valencia": require("../assets/player_photos_custom/Edwin Valencia.png"),
  "Eero Markkanen": require("../assets/player_photos_custom/Eero Markkanen.png"),
  "Emanuele D'Anna": require("../assets/player_photos_custom/Emanuele D'Anna.png"),
  "Emilio Guerra": require("../assets/player_photos_custom/Emilio Guerra.png"),
  "Emir Murati": require("../assets/player_photos_custom/Emir Murati.png"),
  "Eric Smith": require("../assets/player_photos_custom/Eric Smith.png"),
  "Etienne Eto'o": require("../assets/player_photos_custom/Etienne Eto'o.png"),
  "Eugenio D'Ursi": require("../assets/player_photos_custom/Eugenio D'Ursi.png"),
  "Ezechiel N'Douassel": require("../assets/player_photos_custom/Ezechiel N'Douassel.png"),
  "Ezequiel Mastrolía": require("../assets/player_photos_custom/Ezequiel Mastrolía.png"),
  "Felice D'Amico": require("../assets/player_photos_custom/Felice D'Amico.png"),
  "Felix Ruml": require("../assets/player_photos_custom/Felix Ruml.png"),
  "Ferdinand Oswald": require("../assets/player_photos_custom/Ferdinand Oswald.png"),
  "Fernando Fernández": require("../assets/player_photos_custom/Fernando Fernández.png"),
  "Fernando López": require("../assets/player_photos_custom/Fernando López.png"),
  "Fernando Varela": require("../assets/player_photos_custom/Fernando Varela.png"),
  "Ferris N'Goma": require("../assets/player_photos_custom/Ferris N'Goma.png"),
  "Fidel Martínez": require("../assets/player_photos_custom/Fidel Martínez.png"),
  "Francesco D'Alessio": require("../assets/player_photos_custom/Francesco D'Alessio.png"),
  "Francesco Tahiraj": require("../assets/player_photos_custom/Francesco Tahiraj.png"),
  "Franklin Guerra": require("../assets/player_photos_custom/Franklin Guerra.png"),
  "Furkan Şeker": require("../assets/player_photos_custom/Furkan Şeker.png"),
  "Gabriele Moncini": require("../assets/player_photos_custom/Gabriele Moncini.png"),
  "Gary O'Neill": require("../assets/player_photos_custom/Gary O'Neill.png"),
  "Gary Phillips": require("../assets/player_photos_custom/Gary Phillips.png"),
  "George Tanner": require("../assets/player_photos_custom/George Tanner.png"),
  "George Weah Jr.": require("../assets/player_photos_custom/George Weah Jr..png"),
  "George Wickens": require("../assets/player_photos_custom/George Wickens.png"),
  "Giovanni Martina": require("../assets/player_photos_custom/Giovanni Martina.png"),
  "Goku Román": require("../assets/player_photos_custom/Goku Román.png"),
  "Gonzalo Bergessio": require("../assets/player_photos_custom/Gonzalo Bergessio.png"),
  "Gunnar Nielsen": require("../assets/player_photos_custom/Gunnar Nielsen.png"),
  "Henry Smith": require("../assets/player_photos_custom/Henry Smith.png"),
  "Houcine Rabii": require("../assets/player_photos_custom/Houcine Rabii.png"),
  "Ilombe Mboyo": require("../assets/player_photos_custom/Ilombe Mboyo.png"),
  "Ismail H'Maidat": require("../assets/player_photos_custom/Ismail H'Maidat.png"),
  "Jack Harrington": require("../assets/player_photos_custom/Jack Harrington.png"),
  "Jack McIntyre": require("../assets/player_photos_custom/Jack McIntyre.png"),
  "Jack O'Connell": require("../assets/player_photos_custom/Jack O'Connell.png"),
  "Jack Parry": require("../assets/player_photos_custom/Jack Parry.png"),
  "Jacob Young": require("../assets/player_photos_custom/Jacob Young.png"),
  "James Eto'o": require("../assets/player_photos_custom/James Eto'o.png"),
  "James Melhado": require("../assets/player_photos_custom/James Melhado.png"),
  "Jamie O'Hara": require("../assets/player_photos_custom/Jamie O'Hara.png"),
  "Jannik Rochelt": require("../assets/player_photos_custom/Jannik Rochelt.png"),
  "Jason": require("../assets/player_photos_custom/Jason.png"),
  "Jean N'Guessan": require("../assets/player_photos_custom/Jean N'Guessan.png"),
  "Jérémy Guillemenot": require("../assets/player_photos_custom/Jérémy Guillemenot.png"),
  "Jerry St. Juste": require("../assets/player_photos_custom/Jerry St. Juste.png"),
  "Jimer Fory": require("../assets/player_photos_custom/Jimer Fory.png"),
  "Joan Campins": require("../assets/player_photos_custom/Joan Campins.png"),
  "Joan Luque": require("../assets/player_photos_custom/Joan Luque.png"),
  "Joao Villamarín": require("../assets/player_photos_custom/Joao Villamarín.png"),
  "Joe Martin": require("../assets/player_photos_custom/Joe Martin.png"),
  "Joe O'Brien-Whitmarsh": require("../assets/player_photos_custom/Joe O'Brien-Whitmarsh.png"),
  "Joe Walters": require("../assets/player_photos_custom/Joe Walters.png"),
  "Johan Arango": require("../assets/player_photos_custom/Johan Arango.png"),
  "John Brooks": require("../assets/player_photos_custom/John Brooks.png"),
  "John Clarke": require("../assets/player_photos_custom/John Clarke.png"),
  "John Kennedy": require("../assets/player_photos_custom/John Kennedy.png"),
  "Jon Bakero": require("../assets/player_photos_custom/Jon Bakero.png"),
  "Jonathan de la Cruz": require("../assets/player_photos_custom/Jonathan de la Cruz.png"),
  "Jordan Larsson": require("../assets/player_photos_custom/Jordan Larsson.png"),
  "Jorge Arias": require("../assets/player_photos_custom/Jorge Arias.png"),
  "Jorge Félix": require("../assets/player_photos_custom/Jorge Félix.png"),
  "José Francisco Cevallos": require("../assets/player_photos_custom/José Francisco Cevallos.png"),
  "Josh O'Hanlon": require("../assets/player_photos_custom/Josh O'Hanlon.png"),
  "Joss Didiba": require("../assets/player_photos_custom/Joss Didiba.png"),
  "Julián Mina": require("../assets/player_photos_custom/Julián Mina.png"),
  "Julio Cruz": require("../assets/player_photos_custom/Julio Cruz.png"),
  "Julio Iglesias": require("../assets/player_photos_custom/Julio Iglesias.png"),
  "Justin Butler": require("../assets/player_photos_custom/Justin Butler.png"),
  "Karl-Heinz Lappe": require("../assets/player_photos_custom/Karl-Heinz Lappe.png"),
  "Keelan O'Connell": require("../assets/player_photos_custom/Keelan O'Connell.png"),
  "Kevin Berkoe": require("../assets/player_photos_custom/Kevin Berkoe.png"),
  "Kevin Mina": require("../assets/player_photos_custom/Kevin Mina.png"),
  "Kévin N'Doram": require("../assets/player_photos_custom/Kévin N'Doram.png"),
  "Kevin O'Connor": require("../assets/player_photos_custom/Kevin O'Connor.png"),
  "Kieran O'Hara": require("../assets/player_photos_custom/Kieran O'Hara.png"),
  "Kike García": require("../assets/player_photos_custom/Kike García.png"),
  "Lee O'Connor": require("../assets/player_photos_custom/Lee O'Connor.png"),
  "Leon Fesser": require("../assets/player_photos_custom/Leon Fesser.png"),
  "Lewis O'Brien": require("../assets/player_photos_custom/Lewis O'Brien.png"),
  "Liam Loughlan": require("../assets/player_photos_custom/Liam Loughlan.png"),
  "Liam O'Brien": require("../assets/player_photos_custom/Liam O'Brien.png"),
  "Lin Liangming": require("../assets/player_photos_custom/Lin Liangming.png"),
  "Lloyd Jones": require("../assets/player_photos_custom/Lloyd Jones.png"),
  "Louis Wagner": require("../assets/player_photos_custom/Louis Wagner.png"),
  "Luca Buongiorno": require("../assets/player_photos_custom/Luca Buongiorno.png"),
  "Luca D'Andrea": require("../assets/player_photos_custom/Luca D'Andrea.png"),
  "Lucas Scholl": require("../assets/player_photos_custom/Lucas Scholl.png"),
  "Luciano Boggio": require("../assets/player_photos_custom/Luciano Boggio.png"),
  "Luciano D'Auria-Henry": require("../assets/player_photos_custom/Luciano D'Auria-Henry.png"),
  "Ludovico D'Orazio": require("../assets/player_photos_custom/Ludovico D'Orazio.png"),
  "Luke O'Neill": require("../assets/player_photos_custom/Luke O'Neill.png"),
  "Marc Carmona": require("../assets/player_photos_custom/Marc Carmona.png"),
  "Marcel Zylla": require("../assets/player_photos_custom/Marcel Zylla.png"),
  "Marco D'Alessandro": require("../assets/player_photos_custom/Marco D'Alessandro.png"),
  "Marco D'Aloia": require("../assets/player_photos_custom/Marco D'Aloia.png"),
  "Mark Cullen": require("../assets/player_photos_custom/Mark Cullen.png"),
  "Mark Harris": require("../assets/player_photos_custom/Mark Harris.png"),
  "Mark Hill": require("../assets/player_photos_custom/Mark Hill.png"),
  "Mark O'Mahony": require("../assets/player_photos_custom/Mark O'Mahony.png"),
  "Martin Scott": require("../assets/player_photos_custom/Martin Scott.png"),
  "Marvin Ávila": require("../assets/player_photos_custom/Marvin Ávila.png"),
  "Mathías Rodríguez": require("../assets/player_photos_custom/Mathías Rodríguez.png"),
  "Matías Alustiza": require("../assets/player_photos_custom/Matías Alustiza.png"),
  "Matt McKay": require("../assets/player_photos_custom/Matt McKay.png"),
  "Matthew Dennis": require("../assets/player_photos_custom/Matthew Dennis.png"),
  "Matthias Strohmaier": require("../assets/player_photos_custom/Matthias Strohmaier.png"),
  "Mattia El Hilali": require("../assets/player_photos_custom/Mattia El Hilali.png"),
  "Matty Willock": require("../assets/player_photos_custom/Matty Willock.png"),
  "Mátyás Tajti": require("../assets/player_photos_custom/Mátyás Tajti.png"),
  "Maurício Ramos": require("../assets/player_photos_custom/Maurício Ramos.png"),
  "Maxime D'Arpino": require("../assets/player_photos_custom/Maxime D'Arpino.png"),
  "Maximilian Zaiser": require("../assets/player_photos_custom/Maximilian Zaiser.png"),
  "Mayoro N'Doye": require("../assets/player_photos_custom/Mayoro N'Doye.png"),
  "Michael Bradley": require("../assets/player_photos_custom/Michael Bradley.png"),
  "Michael Richardson": require("../assets/player_photos_custom/Michael Richardson.png"),
  "Miguel Ángel Cordero": require("../assets/player_photos_custom/Miguel Ángel Cordero.png"),
  "Miguel Ángel Ruiz": require("../assets/player_photos_custom/Miguel Ángel Ruiz.png"),
  "Miguel Bañuz": require("../assets/player_photos_custom/Miguel Bañuz.png"),
  "Miguel Martínez de Corta": require("../assets/player_photos_custom/Miguel Martínez de Corta.png"),
  "Mousa Dembélé": require("../assets/player_photos_custom/Mousa Dembélé.png"),
  "Mustafa Aşan": require("../assets/player_photos_custom/Mustafa Aşan.png"),
  "N'dri Philippe Koffi": require("../assets/player_photos_custom/N'dri Philippe Koffi.png"),
  "Necip Uysal": require("../assets/player_photos_custom/Necip Uysal.png"),
  "Niall Thompson": require("../assets/player_photos_custom/Niall Thompson.png"),
  "Nick Ward": require("../assets/player_photos_custom/Nick Ward.png"),
  "Nico O'Reilly": require("../assets/player_photos_custom/Nico O'Reilly.png"),
  "Nicolas Jüllich": require("../assets/player_photos_custom/Nicolas Jüllich.png"),
  "Nigel Hasselbaink": require("../assets/player_photos_custom/Nigel Hasselbaink.png"),
  "Noé Acosta": require("../assets/player_photos_custom/Noé Acosta.png"),
  "Oliver Kilner": require("../assets/player_photos_custom/Oliver Kilner.png"),
  "Ollie O'Neill": require("../assets/player_photos_custom/Ollie O'Neill.png"),
  "Omar Tejeda": require("../assets/player_photos_custom/Omar Tejeda.png"),
  "Onur Bayramoğlu": require("../assets/player_photos_custom/Onur Bayramoğlu.png"),
  "Oriol Rosell": require("../assets/player_photos_custom/Oriol Rosell.png"),
  "Óscar Díaz": require("../assets/player_photos_custom/Óscar Díaz.png"),
  "Oscar Lewicki": require("../assets/player_photos_custom/Oscar Lewicki.png"),
  "Özgür Özkaya": require("../assets/player_photos_custom/Özgür Özkaya.png"),
  "Pape M'Bow": require("../assets/player_photos_custom/Pape M'Bow.png"),
  "Paudie O'Connor": require("../assets/player_photos_custom/Paudie O'Connor.png"),
  "Paul Will": require("../assets/player_photos_custom/Paul Will.png"),
  "Pedro Larrea": require("../assets/player_photos_custom/Pedro Larrea.png"),
  "Pedro Pablo Velasco": require("../assets/player_photos_custom/Pedro Pablo Velasco.png"),
  "Peter Stroud": require("../assets/player_photos_custom/Peter Stroud.png"),
  "Pierre Bourdin": require("../assets/player_photos_custom/Pierre Bourdin.png"),
  "Raif Husic": require("../assets/player_photos_custom/Raif Husic.png"),
  "Raïs M'Bolhi": require("../assets/player_photos_custom/Raïs M'Bolhi.png"),
  "Renato Ibarra": require("../assets/player_photos_custom/Renato Ibarra.png"),
  "Ricardo Noir": require("../assets/player_photos_custom/Ricardo Noir.png"),
  "Riccardo Innocenti": require("../assets/player_photos_custom/Riccardo Innocenti.png"),
  "Riccardo Mattelli": require("../assets/player_photos_custom/Riccardo Mattelli.png"),
  "Richie Baker": require("../assets/player_photos_custom/Richie Baker.png"),
  "Rico Lewis": require("../assets/player_photos_custom/Rico Lewis.png"),
  "Robbie McDaid": require("../assets/player_photos_custom/Robbie McDaid.png"),
  "Robert Costa": require("../assets/player_photos_custom/Robert Costa.png"),
  "Rodrigo Muniz": require("../assets/player_photos_custom/Rodrigo Muniz.png"),
  "Rodrigo Tarín": require("../assets/player_photos_custom/Rodrigo Tarín.png"),
  "Romain Habran": require("../assets/player_photos_custom/Romain Habran.png"),
  "Roman Macek": require("../assets/player_photos_custom/Roman Macek.png"),
  "Roosevelt Oyola": require("../assets/player_photos_custom/Roosevelt Oyola.png"),
  "Roy O'Donovan": require("../assets/player_photos_custom/Roy O'Donovan.png"),
  "Rubén Belima": require("../assets/player_photos_custom/Rubén Belima.png"),
  "Saër Sène": require("../assets/player_photos_custom/Saër Sène.png"),
  "Salvatore D'Elia": require("../assets/player_photos_custom/Salvatore D'Elia.png"),
  "Santiago Villafañe": require("../assets/player_photos_custom/Santiago Villafañe.png"),
  "Sergio Aguza": require("../assets/player_photos_custom/Sergio Aguza.png"),
  "Sessi D'Almeida": require("../assets/player_photos_custom/Sessi D'Almeida.png"),
  "Seydine N'Diaye": require("../assets/player_photos_custom/Seydine N'Diaye.png"),
  "Shane O'Connor": require("../assets/player_photos_custom/Shane O'Connor.png"),
  "Son": require("../assets/player_photos_custom/Son.png"),
  "Soroush Rafiei": require("../assets/player_photos_custom/Soroush Rafiei.png"),
  "Stefano Pellizzari": require("../assets/player_photos_custom/Stefano Pellizzari.png"),
  "Stefano Turco": require("../assets/player_photos_custom/Stefano Turco.png"),
  "Stephen Wearne": require("../assets/player_photos_custom/Stephen Wearne.png"),
  "Stoichkov": require("../assets/player_photos_custom/Stoichkov.png"),
  "Stuart O'Keefe": require("../assets/player_photos_custom/Stuart O'Keefe.png"),
  "Szymon Matuszek": require("../assets/player_photos_custom/Szymon Matuszek.png"),
  "Tasos Donis": require("../assets/player_photos_custom/Tasos Donis.png"),
  "Taylor Booth": require("../assets/player_photos_custom/Taylor Booth.png"),
  "Thomas Mayer": require("../assets/player_photos_custom/Thomas Mayer.png"),
  "Thuram": require("../assets/player_photos_custom/Thuram.png"),
  "Tito Valencia": require("../assets/player_photos_custom/Tito Valencia.png"),
  "Tom Barlow": require("../assets/player_photos_custom/Tom Barlow.png"),
  "Tom Broadbent": require("../assets/player_photos_custom/Tom Broadbent.png"),
  "Tom Leahy": require("../assets/player_photos_custom/Tom Leahy.png"),
  "Tom Scully": require("../assets/player_photos_custom/Tom Scully.png"),
  "Tom Sparrow": require("../assets/player_photos_custom/Tom Sparrow.png"),
  "Tom Spencer": require("../assets/player_photos_custom/Tom Spencer.png"),
  "Tommi O'Reilly": require("../assets/player_photos_custom/Tommi O'Reilly.png"),
  "Tommy Doyle": require("../assets/player_photos_custom/Tommy Doyle.png"),
  "True Grant": require("../assets/player_photos_custom/True Grant.png"),
  "Tyler Boyd": require("../assets/player_photos_custom/Tyler Boyd.png"),
  "Víctor Barberà": require("../assets/player_photos_custom/Víctor Barberà.png"),
  "Vincent Pajot": require("../assets/player_photos_custom/Vincent Pajot.png"),
  "Vincenzo Fiorillo": require("../assets/player_photos_custom/Vincenzo Fiorillo.png"),
  "Walter Cárdenas": require("../assets/player_photos_custom/Walter Cárdenas.png"),
  "Warren O'Hora": require("../assets/player_photos_custom/Warren O'Hora.png"),
  "Yann M'Vila": require("../assets/player_photos_custom/Yann M'Vila.png"),
  "Yannis M'Bemba": require("../assets/player_photos_custom/Yannis M'Bemba.png"),
  "Yannis N'Gakoutou": require("../assets/player_photos_custom/Yannis N'Gakoutou.png"),
  "Youssouf M'Changama": require("../assets/player_photos_custom/Youssouf M'Changama.png"),
  "Yunus Musah": require("../assets/player_photos_custom/Yunus Musah.png"),
};

export const LOCAL_PLAYER_PHOTOS = Object.fromEntries(
  Object.entries(LOCAL_PLAYER_PHOTO_MODULES).map(([name, mod]) => [
    name,
    Image.resolveAssetSource(mod).uri,
  ])
);
