// Prototip veri seti — web MVP ile birebir aynı. Üretimde lisanslı/doğrulanmış
// bir kaynakla (bkz. proje notları) değiştirilmeli. supabase/seed.sql bu diziden
// gen_seed.js ile üretildi, ikisi birbirinden sapmasın diye burada da saklanıyor.
export const PLAYERS = [
  { name: "Arda Turan", clubs: ["Galatasaray", "Atletico Madrid", "Barcelona", "Başakşehir"] },
  { name: "Burak Yılmaz", clubs: ["Trabzonspor", "Beşiktaş", "Galatasaray", "Lille", "Monaco", "Adana Demirspor"] },
  { name: "Hakan Şükür", clubs: ["Galatasaray", "Torino", "Inter", "Parma", "Beşiktaş"] },
  { name: "Emre Belözoğlu", clubs: ["Galatasaray", "Inter", "Newcastle United", "Atletico Madrid", "Fenerbahçe"] },
  { name: "Rüştü Reçber", clubs: ["Fenerbahçe", "Barcelona", "Beşiktaş"] },
  { name: "Wesley Sneijder", clubs: ["Ajax", "Real Madrid", "Inter", "Galatasaray", "Nice"] },
  { name: "Didier Drogba", clubs: ["Marseille", "Chelsea", "Galatasaray", "Shanghai Shenhua"] },
  { name: "Robinho", clubs: ["Santos", "Real Madrid", "Manchester City", "AC Milan", "Sivasspor"] },
  { name: "Roberto Carlos", clubs: ["Real Madrid", "Fenerbahçe", "Corinthians"] },
  { name: "Alex de Souza", clubs: ["Fenerbahçe", "Palmeiras", "Coritiba"] },
  { name: "Mario Gomez", clubs: ["Bayern Munich", "Fiorentina", "Beşiktaş", "VfL Wolfsburg", "Stuttgart"] },
  { name: "Nani", clubs: ["Sporting CP", "Manchester United", "Fenerbahçe", "Valencia", "Lazio"] },
  { name: "Fernando Muslera", clubs: ["Lazio", "Galatasaray"] },
  { name: "Mesut Özil", clubs: ["Werder Bremen", "Real Madrid", "Arsenal", "Fenerbahçe", "Başakşehir"] },
  { name: "Robin van Persie", clubs: ["Feyenoord", "Arsenal", "Manchester United", "Fenerbahçe"] },
  { name: "Samuel Eto'o", clubs: ["Real Madrid", "Barcelona", "Inter", "Chelsea", "Everton", "Antalyaspor", "Konyaspor"] },
  { name: "Jose Sosa", clubs: ["Estudiantes", "Bayern Munich", "Atletico Madrid", "Napoli", "Trabzonspor", "Beşiktaş"] },
  { name: "Ryan Babel", clubs: ["Ajax", "Liverpool", "Hoffenheim", "Fulham", "Beşiktaş", "Galatasaray"] },
  { name: "Bafetimbi Gomis", clubs: ["Lyon", "Swansea", "Marseille", "Galatasaray"] },
  { name: "Lukas Podolski", clubs: ["Köln", "Bayern Munich", "Arsenal", "Inter", "Galatasaray", "Antalyaspor"] },
  { name: "Marouane Fellaini", clubs: ["Standard Liège", "Everton", "Manchester United", "Shandong Taishan"] },
  { name: "Younes Belhanda", clubs: ["Nice", "Dynamo Kyiv", "Galatasaray", "Montpellier"] },
  { name: "Marek Hamsik", clubs: ["Napoli", "Göztepe", "Trabzonspor"] },
  { name: "Dries Mertens", clubs: ["PSV", "Napoli", "Galatasaray", "Antalyaspor"] },
  { name: "Radamel Falcao", clubs: ["River Plate", "Porto", "Atletico Madrid", "Monaco", "Manchester United", "Chelsea", "Galatasaray"] },
  { name: "Filip Kostic", clubs: ["Stuttgart", "Hamburg", "Eintracht Frankfurt", "Juventus", "Fenerbahçe"] },
  { name: "Kevin-Prince Boateng", clubs: ["Tottenham", "Portsmouth", "AC Milan", "Schalke 04", "Beşiktaş", "Fiorentina"] },
  { name: "Ricardo Quaresma", clubs: ["Sporting CP", "Barcelona", "Inter", "Porto", "Beşiktaş"] },
  { name: "Gökhan Gönül", clubs: ["Fenerbahçe", "Beşiktaş", "Monaco"] },
  { name: "Colin Kazim-Richards", clubs: ["Fenerbahçe", "Beşiktaş", "Bursaspor", "Feyenoord"] },
  { name: "Mevlüt Erdinç", clubs: ["Sochaux", "Saint-Étienne", "Galatasaray", "Sivasspor"] },
  { name: "Milan Baros", clubs: ["Liverpool", "Aston Villa", "Lyon", "Galatasaray"] },
  { name: "Elano", clubs: ["Shakhtar Donetsk", "Manchester City", "Galatasaray"] },
  { name: "Felipe Melo", clubs: ["Fiorentina", "Juventus", "Galatasaray", "Palmeiras"] },
  { name: "Steven Nzonzi", clubs: ["Sevilla", "Roma", "Galatasaray", "Rennes"] },
  { name: "Emmanuel Emenike", clubs: ["Fenerbahçe", "Spartak Moscow", "Olympiacos"] },
  { name: "Moussa Sow", clubs: ["Rennes", "Lille", "Fenerbahçe", "Trabzonspor", "Antalyaspor"] },
  { name: "Serdar Taşçı", clubs: ["Stuttgart", "Roma", "Galatasaray", "Eintracht Frankfurt"] },
  { name: "Cenk Tosun", clubs: ["Beşiktaş", "Everton", "Crystal Palace"] },
  { name: "Umut Bulut", clubs: ["Trabzonspor", "Galatasaray", "Kayserispor"] },
  { name: "Hugo Almeida", clubs: ["Werder Bremen", "Beşiktaş", "Olympiacos"] },
  { name: "Demba Ba", clubs: ["Chelsea", "Beşiktaş", "Shanghai Shenhua", "West Ham"] },
  { name: "Alex Teixeira", clubs: ["Shakhtar Donetsk", "Beşiktaş", "Jiangsu Suning"] },
  { name: "Talisca", clubs: ["Benfica", "Beşiktaş", "Guangzhou Evergrande", "Al-Nassr", "Fenerbahçe"] },
  { name: "Vincent Aboubakar", clubs: ["Valenciennes", "Lorient", "Porto", "Beşiktaş", "Al-Nassr"] },
  { name: "Andre Ayew", clubs: ["Marseille", "Swansea", "West Ham", "Fenerbahçe", "Al Sadd"] },
  { name: "Bruma", clubs: ["Sporting CP", "Galatasaray", "RB Leipzig", "PAOK", "Fenerbahçe"] },
  { name: "Khvicha Kvaratskhelia", clubs: ["Napoli", "PSG"] },
];
